spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: user@gmail.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jackson:
    default-property-inclusion: NON_NULL
