drop table if exists _users cascade;
drop table if exists tasks cascade;

create table _users (id bigint generated by default as identity, password varchar(255), role varchar(255) check (role in ('USER','ADMIN')), user_name varchar(255), primary key (id));
create table tasks (assigned_user_id bigint, author_user_id bigint, create_date timestamp(6), due_date timestamp(6), id bigint generated by default as identity, update_date timestamp(6), description varchar(255), priority varchar(255) check (priority in ('LOW','MEDIUM','HIGH')), status varchar(255) check (status in ('TODO','IN_PROGRESS','DONE')), title varchar(255), primary key (id));

alter table if exists tasks add constraint FKtc5fcmcyixeeik28hf95g38an foreign key (assigned_user_id) references _users;
alter table if exists tasks add constraint FKg8sw5w33x280pebv8maifd8uk foreign key (author_user_id) references _users;

create index idx_user_name on _users (user_name);
create index idx_task_id on tasks (id);
